// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static final FirebaseOptions web = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WEB_API_KEY']!,
    appId: dotenv.env['FIREBASE_WEB_PROJECT_ID']!,
    messagingSenderId: '424439546938',
    projectId: 'latinone-1',
    authDomain: 'latinone-1.firebaseapp.com',
    storageBucket: 'latinone-1.appspot.com',
    measurementId: 'G-6T2X6XR3XV',
  );

  static final FirebaseOptions android = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_ANDROID_API_KEY']!,
    appId: dotenv.env['FIREBASE_ANDROID_PROJECT_ID']!,
    messagingSenderId: '424439546938',
    projectId: 'latinone-1',
    storageBucket: 'latinone-1.appspot.com',
  );

  static final FirebaseOptions ios = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_IOS_API_KEY']!,
    appId: dotenv.env['FIREBASE_IOS_PROJECT_ID']!,
    messagingSenderId: '424439546938',
    projectId: 'latinone-1',
    storageBucket: 'latinone-1.appspot.com',
    iosBundleId: 'com.example.latinOne',
  );

  static final FirebaseOptions macos = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_MACOS_API_KEY']!,
    appId: dotenv.env['FIREBASE_MACOS_PROJECT_ID']!,
    messagingSenderId: '424439546938',
    projectId: 'latinone-1',
    storageBucket: 'latinone-1.appspot.com',
    iosBundleId: 'com.example.latinOne',
  );

  static final FirebaseOptions windows = FirebaseOptions(
    apiKey: dotenv.env['FIREBASE_WINDOWS_API_KEY']!,
    appId: dotenv.env['FIREBASE_WINDOWS_PROJECT_ID']!,
    messagingSenderId: '424439546938',
    projectId: 'latinone-1',
    authDomain: 'latinone-1.firebaseapp.com',
    storageBucket: 'latinone-1.appspot.com',
    measurementId: 'G-NLH3CJ2BQQ',
  );
}